##  THESE SETTING SHOULD NOT NEED TO BE SECURE.  IF YOU NEED TO USE SECURE
##  SETTINGS USE -- config/config.yml AND FOLLOW THE INSTRUCTIONS ON THAT PAGE
##  TO DEPLOY

require 'yaml'

SETTINGS = {
  :use_foreign_keys => false
}